"""
    Configuration file for pyHoliday.

    This file holds all of your general settings along with program specific
    settings.

    Ideas:
    - Alternative config setup options.
"""

# General Setup
setup:
  loop: Yes # Options: Yes or No
  sleep: 45 # Any time (minutes)
  platform: Linux # Linux, Chip or (Pi [Not implemented yet])

linux:
  # Alarm Program
  trigger_key: # (Key to start program [Not implemented yet!])

chip:
  # Alarm Program
  trigger_pin: CSID0 # GPIO Pin on Chip to trigger program
  Relay_pin: CSID2 # GPIO Pin on Chip to trigger light relay

alarm:
  intro: activate.mp3 # Audio file (mp3) to be played (place in audio folder!)
  alarm: alarm.mp3 # Audio file (mp3) to be played (place in audio folder!)
  voice: voice.mp3 # Audio file (mp3) to be played (place in audio folder!)
